/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBtest;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.ListIterator;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.sql.Statement;
import java.sql.Connection;

/**
 *
 * @author arvid
 */
public class UpdateraAlienInf extends javax.swing.JFrame {

    private static InfDB idb;
    private String enData;
    private String valdAlien;
    private String ras;

    public UpdateraAlienInf(InfDB iidb) {
        initComponents();
        idb = iidb;
        fillAlienCmb();
        fillTextFields();
        firstCmb();

    }

    private void fillAlienCmb() {
        try {
            ArrayList<String> aliens = new ArrayList<String>();
            String alienFraga = "SELECT namn FROM alien";
            aliens = idb.fetchColumn(alienFraga);
            for (String alien : aliens) {
                alienCmb.addItem(alien);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alienCmb = new javax.swing.JComboBox<>();
        losenordField = new javax.swing.JTextField();
        regField = new javax.swing.JTextField();
        telField = new javax.swing.JTextField();
        platsField = new javax.swing.JTextField();
        namnField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ansCmb = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        rasCmb = new javax.swing.JComboBox<>();
        extraRasField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        extraRasLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        alienCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienCmbActionPerformed(evt);
            }
        });

        jButton1.setText("Uppdatera");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Lösenord:");

        jLabel2.setText("Ansvarig agent:");

        jLabel3.setText("Registrerad:");

        jLabel4.setText("Telefonnummer:");

        jLabel5.setText("Plats:");

        jLabel7.setText("Namn");

        jLabel8.setText("Ras:");

        rasCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boglodite", "Worm", "Squid" }));
        rasCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rasCmbActionPerformed(evt);
            }
        });

        extraRasLabel.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(146, 146, 146)
                            .addComponent(rasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addGap(167, 167, 167)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(extraRasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(36, 36, 36)
                                    .addComponent(extraRasField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)
                                    .addGap(37, 37, 37)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namnField)
                            .addComponent(losenordField)
                            .addComponent(regField)
                            .addComponent(telField)
                            .addComponent(platsField)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(alienCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ansCmb, 0, 165, Short.MAX_VALUE))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(alienCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(losenordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ansCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(platsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(namnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extraRasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraRasLabel))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alienCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienCmbActionPerformed
        // TODO add your handling code here:
        valdAlien = alienCmb.getSelectedItem().toString();
        fillTextFields();
    }//GEN-LAST:event_alienCmbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean rattInputLosenord = false;
        boolean rattInputNamn = false;
        boolean rattInputAns = false;

        try {
            String namn = namnField.getText();
            if (namn.length() != 0) {
                rattInputNamn = true;
            } else {
                JOptionPane.showMessageDialog(null, "Du måste fylla i ett nytt namn");
            }
            String losenord = losenordField.getText();
            if (losenord.length() < 7) {
                rattInputLosenord = true;
            } else {
                JOptionPane.showMessageDialog(null, "Ditt nya lösenord måste vara mindre än 7 tecken");
            }
            String ansvarig = ansCmb.getSelectedItem().toString();
            String ansFraga = "SELECT agent_ID FROM agent where namn = '" + ansvarig + "'";
            String ansvarigAgentID = idb.fetchSingle(ansFraga);
            //ta ut id:t från den agent som är ansvarig för att få in rätt i databasen

            String reg = regField.getText();
            String plats = platsField.getText();
            //ta ut id:t från den plats som anges för att det ska bli rätt i databasen
            String platsIDFraga = "SELECT Plats_ID from plats inner join alien a on plats.Plats_ID = a.Plats WHERE Benamning = '" + plats + "' LIMIT 1";
            String platsID = idb.fetchSingle(platsIDFraga);

            String idFraga = "Select Alien_ID FROM alien where namn = '" + valdAlien + "'";
            String id = idb.fetchSingle(idFraga);
            String tel = telField.getText();
            Validation validering = new Validation(losenord);
            boolean test = validering.testaString(losenord);
            Validation validering2 = new Validation(plats);
            boolean test2 = validering2.testaString(plats);

            Validation validering3 = new Validation(reg);
            boolean test3 = validering3.testaString(reg);

            Validation validering5 = new Validation(tel);
            boolean test5 = validering5.testaString(tel);

            Validation validering6 = new Validation(namn);
            boolean test6 = validering6.testaString(namn);

            if (test == true && test2 == true && test3 == true && test5 == true && test6 == true) {
                String updateraAlienFraga = "UPDATE alien SET Registreringsdatum = '" + reg + "', Losenord = '" + losenord + "',\n"
                        + "Namn = '" + namn + "', Telefon = '" + tel + "', Plats = '" + platsID + "', Ansvarig_Agent = '" + ansvarigAgentID + "' where namn = '" + namn + "'";
                idb.update(updateraAlienFraga);
            }
            ras = rasCmb.getSelectedItem().toString();
            switch (ras) {
                case "Squid":

                    String antal_armar = extraRasField.getText();

                    Validation validering7 = new Validation(antal_armar);
                    boolean test7 = validering7.kollaInt(antal_armar);
                    if (test5 == true) {
                        String rasFraga = "UPDATE Squid SET antal_armar = '" + antal_armar + "' where Alien_ID = '" + id + "'";
                        idb.update(rasFraga);
                    }
                    break;
                case "Boglodite":

                    String antal_boogies = extraRasField.getText();

                    Validation validering8 = new Validation(antal_boogies);
                    boolean test8 = validering8.kollaInt(antal_boogies);
                    if (test6 == true) {
                        System.out.println(id);
                        String rasFraga = "UPDATE boglodite SET antal_boogies = '" + antal_boogies + "' where Alien_ID = '" + id + "'";
                        idb.update(rasFraga);
                    }
                    break;
                case "Worm":
                    String rasFraga = "UPDATE worm set Alien_ID ='" + id + "'";
                    idb.update(rasFraga);
                    break;
                default:
                    break;
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void firstCmb() {
        extraRasLabel.setText("Antal Boogies");
        extraRasLabel.setVisible(true);
        extraRasField.setVisible(true);
    }
    private void rasCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rasCmbActionPerformed
        // TODO add your handling code here:
        ras = rasCmb.getSelectedItem().toString();
        switch (ras) {
            case "Squid":
                extraRasLabel.setText("Antal Armar");
                extraRasLabel.setVisible(true);
                extraRasField.setVisible(true);
                break;
            case "Boglodite":
                extraRasLabel.setText("Antal Boogies");
                extraRasLabel.setVisible(true);
                extraRasField.setVisible(true);
                break;
            case "Worm":
                extraRasLabel.setVisible(false);
                extraRasField.setVisible(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_rasCmbActionPerformed
    private void fillTextFields() {
        try {

            String fraga = "SELECT * FROM alien WHERE namn = '" + valdAlien + "'";
            HashMap<String, String> varden = new HashMap<String, String>();
            varden = idb.fetchRow(fraga);
            int i = 0;
            namnField.setText(valdAlien);
            for (String data : varden.values()) {
                enData = data;
                while (i <= varden.size()) {
                    if (i == 1) {
                        losenordField.setText(enData);
                    }
                    if (i == 2) {
                        ArrayList<String> agentNamn = new ArrayList<String>();
                        String ansAgentFraga = "SELECT namn FROM agent ORDER BY namn ASC";
                        agentNamn = idb.fetchColumn(ansAgentFraga);
                        for (String namn : agentNamn) {
                            ansCmb.addItem(namn);
                        }

                    }
                    if (i == 3) {
                        regField.setText(enData);
                    }
                    if (i == 4) {
                        telField.setText(enData);
                    }
                    if (i == 5) {
                        String platsFraga = "SELECT plats.benamning FROM plats\n"
                                + "inner join alien a on plats.Plats_ID = a.Plats\n"
                                + "where Plats = '" + enData + "' LIMIT 1";
                        String plats = idb.fetchSingle(platsFraga);
                        platsField.setText(plats);
                    }

                    break;
                }
                i++;
            }

        } catch (Exception ex) {
            System.out.println(ex);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateraAlienInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateraAlienInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateraAlienInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateraAlienInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateraAlienInf(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alienCmb;
    private javax.swing.JComboBox<String> ansCmb;
    private javax.swing.JTextField extraRasField;
    private javax.swing.JLabel extraRasLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField losenordField;
    private javax.swing.JTextField namnField;
    private javax.swing.JTextField platsField;
    private javax.swing.JComboBox<String> rasCmb;
    private javax.swing.JTextField regField;
    private javax.swing.JTextField telField;
    // End of variables declaration//GEN-END:variables
}
